name: 'IT-Bot'
description: 'Read the issues, open the tickets, rinse, repeat'
inputs:
  GITHUB_TOKEN:
    description: |
      Token to authenticate the request
    required: true
runs:
  using: node12
  main: index.js
