on:
  issue_comment:
    types: [created, edited]
jobs:
  bot:
    runs-on: ubuntu-latest
    name: Run the program
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - name: Run action
      uses: teakopp/it-bot@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
